# Generated by Django 3.2.12 on 2022-03-28 10:12

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='profile',
            name='average_score',
        ),
        migrations.AlterField(
            model_name='profile',
            name='games_played',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(blank=True, max_length=50, null=True),
        ),
    ]
