# Generated by Django 3.2.12 on 2022-03-28 10:13

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('accounts', '0002_auto_20220328_1312'),
    ]

    operations = [
        migrations.AlterField(
            model_name='profile',
            name='games_played',
            field=models.IntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='profile',
            name='total_score',
            field=models.IntegerField(blank=True, default=0),
        ),
    ]
