# Generated by Django 3.2.12 on 2022-03-28 10:41

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
    ]

    operations = [
        migrations.CreateModel(
            name='Question',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('question', models.TextField(blank=True)),
                ('correct_answer', models.CharField(blank=True, max_length=40)),
                ('answer_2', models.CharField(blank=True, max_length=40)),
                ('answer_3', models.CharField(blank=True, max_length=40)),
                ('answer_4', models.CharField(blank=True, max_length=40)),
                ('difficulty', models.CharField(choices=[('easy', 'easy'), ('normal', 'normal'), ('hard', 'hard')], max_length=10)),
            ],
        ),
        migrations.CreateModel(
            name='GameSession',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('qustions_list', models.CharField(blank=True, max_length=40, null=True)),
                ('last_answered_question', models.IntegerField(default=0)),
                ('game_finished', models.BooleanField(default=False)),
                ('jokers_used', models.IntegerField(default=0)),
                ('user', models.OneToOneField(on_delete=django.db.models.deletion.CASCADE, to=settings.AUTH_USER_MODEL)),
            ],
        ),
    ]
