# Generated by Django 3.2.12 on 2022-03-28 11:33

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0001_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='gamesession',
            old_name='qustions_list',
            new_name='questions_list',
        ),
    ]
