# Generated by Django 3.2.12 on 2022-03-29 08:49

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0002_rename_qustions_list_gamesession_questions_list'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='game_finished',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='questions_list',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
