# Generated by Django 3.2.12 on 2022-03-30 07:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0003_auto_20220329_1149'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='gamesession',
            name='jokers_used',
        ),
        migrations.AddField(
            model_name='gamesession',
            name='joker_1',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='joker_2',
            field=models.BooleanField(default=False),
        ),
        migrations.AddField(
            model_name='gamesession',
            name='joker_3',
            field=models.BooleanField(default=False),
        ),
    ]
