# Generated by Django 3.2.12 on 2022-03-30 11:11

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('game', '0004_auto_20220330_1030'),
    ]

    operations = [
        migrations.AlterField(
            model_name='gamesession',
            name='joker_1',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='joker_2',
            field=models.IntegerField(default=0),
        ),
        migrations.AlterField(
            model_name='gamesession',
            name='joker_3',
            field=models.IntegerField(default=0),
        ),
    ]
